vich_uploader:
    db_driver: orm


    mappings:
        products:
            uri_prefix: /img/userProfile
            upload_destination: '%kernel.project_dir%/public/img/userProfile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
